name: Build and push Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CURRENT_VERSION: 27.3.0
  BUILD_NUMBER: 0
  LATEST_UBUNTU_VERSION: "24.04"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Nscale
    strategy:
      matrix:
        include:
          - ubuntu_version: "20.04"
            ubuntu_name: "focal"
          - ubuntu_version: "22.04"
            ubuntu_name: "jammy"
          - ubuntu_version: "24.04"
            ubuntu_name: "noble"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_PUSH_USER }}
          password: ${{ secrets.REGISTRY_PUSH_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          ## Only build amd64 for now.
          platforms: linux/amd64
          #platforms: linux/amd64,linux/arm64
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: |
            ${{ vars.REGISTRY_URL }}/inferencing/ubuntu-dind:${{ matrix.ubuntu_name }}-${{ env.CURRENT_VERSION }}
            ${{ vars.REGISTRY_URL }}/inferencing/ubuntu-dind:${{ matrix.ubuntu_name }}-${{ env.CURRENT_VERSION }}-r${{ env.BUILD_NUMBER }}
            ${{ vars.REGISTRY_URL }}/inferencing/ubuntu-dind:${{ matrix.ubuntu_name }}-${{ github.sha}}
            ${{ vars.REGISTRY_URL }}/inferencing/ubuntu-dind:${{ matrix.ubuntu_name }}-${{ env.SHORT_SHA }}
            ${{ matrix.ubuntu_version == env.LATEST_UBUNTU_VERSION && format('{0}/inferencing/ubuntu-dind:latest', vars.REGISTRY_URL) || '' }}
